spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # Springfox version issue
  profiles:
     include: dev
           
#SpringBoot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"