spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # Springfox version issue
  profiles:
     include: local, prod
     default: local
      
#SpringBoot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

---
# local DB
# H2 (In-Memory)
spring:
   config:
      activate:
         on-profile: local
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:monitoring
      username: sa
      password:
   h2:
      console:
         enabled: true
         path: /h2-console
   jpa:
      hibernate:
         ddl-auto: create
      properties:
         hibernate:
            format_sql: true
logging:
  level:
    org:
       hibernate:
          SQL: debug
          type:
             descriptor:
                sql: trace
---
# prod DB
# MariaDB
#spring:
#  config:
#    activate:
#      on-profile: prod
#  datasource:
#     driverClassName: org.mariadb.jdbc.Driver
#     url: jdbc:mariadb://localhost:3306/monitoring?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
#     username: root
#     password: root
#  jpa:
#    database-platform: org.hibernate.dialect.MariaDBDialect
#    hibernate:
#      ddl-auto: update