spring:
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher # Springfox version issue
  profiles: # Multi Profile
    group:
      "local": "localdb, common"
      "prod": "proddb, common"
      "dev": "devdb, common"
      "test": "testdb, common"
      
#SpringBoot Actuator Settings
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"

---
# local DB
# H2 (In-Memory)
spring:
   config:
      activate:
         on-profile: "localdb"
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:monitoring
      username: sohn
      password: sohn
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true\
logging:
  level:
    org:
       hibernate:
          SQL: debug
          type:
             descriptor:
                sql: trace

---
# prod DB
# MariaDB
spring:
  config:
    activate:
      on-profile: "proddb"
  datasource:
     driverClassName: org.mariadb.jdbc.Driver
     url: jdbc:mariadb://localhost:3306/monitoring
     username: monitoring
     password: monitoring
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect

---
# dev DB
# H2 (In-Memory)
spring:
   config:
      activate:
         on-profile: "localdb"
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:monitoring
      username: sohn
      password: sohn
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true\
logging:
  level:
    org:
       hibernate:
          SQL: debug
          type:
             descriptor:
                sql: trace

---
# test DB
# H2 (In-Memory)
spring:
   config:
      activate:
         on-profile: "localdb"
   datasource:
      driver-class-name: org.h2.Driver
      url: jdbc:h2:mem:monitoring
      username: sohn
      password: sohn
   h2:
      console:
         enabled: true
   jpa:
      hibernate:
         ddl-auto: update
      properties:
         hibernate:
            format_sql: true\
logging:
  level:
    org:
       hibernate:
          SQL: debug
          type:
             descriptor:
                sql: trace